### ISSUE TITLE
Better translation for updates.updating.label

### ISSUE THREAD

**Issue by piotrdrag** [aviarypl/mozilla-l10n-pl#105]
updates.updating.label in toolkit/chrome/mozapps/extensions/extensions.dtd is translated as "Aktualizacja dodatków", which is mildly confusing, as this string signals a process that's happening in that moment. The original is "Updating add-ons" and I think "Aktualizowanie dodatków" (or "Uaktualnianie dodatków", if you prefer) would be better.

**Comment by splewako** [comment]
Indeed, "Aktualizowanie dodatków…" would be much better.

**Comment by piotrdrag** [comment]
Do you want me to commit the change? Should I include the ellipsis (the original string doesn't have one)?

**Comment by splewako** [comment]
Yes, please, with ellipsis.
