### ISSUE TITLE
Translate "Relatively" as "stosunkowo"

### ISSUE THREAD

**Issue by piotrdrag** [aviarypl/mozilla-l10n-pl#106]
"Relatively" is currently translated as "relatywnie":

https://transvision.mozfr.org/?recherche=relatively&repo=central&sourcelocale=en-US&locale=pl&search_type=strings

I believe "stosunkowo" would be a more fitting translation.

**Comment by splewako** [comment]
I thought it will be more but is seems it wasn't that big after all. :)
