### ISSUE TITLE
Przetłumaczone zmienne w suite

### ISSUE THREAD

**Issue by piotrdrag** [aviarypl/mozilla-l10n-pl#107]
mail.addr_book.displayName.lastnamefirst i mail.addr_book.show_phonetic_fields w suite/chrome/mailnews/messenger.properties budzą moje wątpliwości:

https://github.com/aviarypl/mozilla-l10n-pl/blob/branches/default/tip/suite/chrome/mailnews/messenger.properties#L255

@adrianer - czy mogę poprawić na "false"?

**Comment by adrianer** [comment]
Mozesz spokojnie poprawic, bo to ewidentny blad ;)
