### ISSUE TITLE
Propozycja tłumaczenia searchFor w suite

### ISSUE THREAD

**Issue by piotrdrag** [aviarypl/mozilla-l10n-pl#108]
searchFor w suite/chrome/browser/navigator.properties wygląda dość niezręcznie ("Szukaj w %S za „%S”"):

https://github.com/aviarypl/mozilla-l10n-pl/blob/branches/default/tip/suite/chrome/browser/navigator.properties#L50

@adrianer - czy mogę zmienić na wersję z browser (i z innego miejsca w suite zresztą też), "Szukaj w %S: „%S”"?

**Comment by adrianer** [comment]
Suma sumarum moja wersja mi sie podobala - ale racja: w praktyce wyglada niezrecznie ;)

Wiec mozesz zmieniac

**Comment by piotrdrag** [comment]
Szczerze, to chyba nie jest po polsku. :)

**Comment by adrianer** [comment]
"Szukaj w pokoju za ukryta zabawka" nie jest po polsku? Jezeli nie to to jest conajmniej po slasku :P

**Comment by piotrdrag** [comment]
Ktoś ostatnio chciał tłumaczyć Firefoksa na śląski, pewnie przydałaby mu się pomoc. :D

**Comment by adrianer** [comment]
Mój śląski sprowadza się głównie do pasywnej znajomości, więc już na tym etapie musiałbym się poddać ;)
