### ISSUE TITLE
Improve useIdleNotifications.label

### ISSUE THREAD

**Issue by splewako** [aviarypl/mozilla-l10n-pl#47]
useIdleNotifications.label "Zezwalaj na natychmiastowe powiadomienia serwera po odebraniu nowej wiadomości" introduced in https://github.com/aviarypl/mozilla-l10n-central-pl/commit/db2e5bffa6fdcee20b8bab2fdc52d75f895296c5 (by @piotrdrag) for https://hg.mozilla.org/comm-central/diff/417f2aaf2ed8/mail/locales/en-US/chrome/messenger/am-server-top.dtd makes no sense to me - is server going to be notified immediately after receiving e-mail message?

**Comment by piotrdrag** [comment]
I can't pretend that I completely understand the original string. Is the server being notified, or the server notifies? I'm open to suggestions on how to translate it better.

**Comment by splewako** [comment]
As I understand [it is still](https://hg.mozilla.org/comm-central/rev/417f2aaf2ed8) about Thunderbird notifying user right away when new messages appear on server and client thanks to [IMAP IDLE](https://en.wikipedia.org/wiki/IMAP_IDLE) (as opposed to time-based routine of asking server for changes since last check, push vs. pull).

**Comment by piotrdrag** [comment]
"Zezwalaj na natychmiastowe powiadomienia z serwera o nowych wiadomościach"?

**Comment by splewako** [comment]
Better but still not good, I don't think Thunderbird delays any notifications… maybe something like "Natychmiast powiadamiaj, gdy serwer odbiera nowe wiadomości" or "Natychmiast powiadamiaj o nowych wiadomościach na serwerze".

**Comment by piotrdrag** [comment]
I like the second one the best.

**Comment by splewako** [comment]
Fixed in https://github.com/aviarypl/mozilla-l10n-central-pl/pull/48
