### ISSUE TITLE
Make netError.dtd *NotFound.longDesc translations more consistent

### ISSUE THREAD

**Issue by splewako** [aviarypl/mozilla-l10n-pl#95]
https://transvision.mozfr.org/?recherche=fileNotFound.longDesc&repo=central&sourcelocale=en-US&locale=pl&search_type=entities also think about fileNotFound.longDesc in https://github.com/aviarypl/mozilla-l10n-central-pl/blame/branches/default/tip/dom/chrome/netError.dtd

**Comment by piotrdrag** [comment]
Anything required on my part?

**Comment by splewako** [comment]
Yes, this affects also `mobile/`, https://transvision.mozfr.org/?recherche=dnsNotFound.longDesc&repo=central&sourcelocale=en-US&locale=pl&search_type=entities

I would like to have those (and possibly others) worded more consistently, even if English version don't exactly match.

**Comment by piotrdrag** [comment]
Feel free to make changes to my modules related to this issue.

**Comment by splewako** [comment]
I think we can close this one.
